[package]
authors = ["Nelson Chen <crazysim@gmail.com>"]
name = "pty_ws"
version = "0.1.0"

[dependencies]
bus = "1.3.2"
filetime = "0.1.14"
nix = "0.9.0"
nix-ptsname_r-shim = "0.1.2"
rouille = "1.0.3"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.4"
time = "0.1.38"
